# Generated by Django 5.0.6 on 2024-07-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masalah', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('features', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ON-GOING', 'On-Going')], max_length=12)),
            ],
        ),
    ]
